# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"

[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[templates]
defer = """{% for file in files %}
zsh-defer source "{{ file }}"
{% endfor %}"""

[plugins.bindkey]
inline = 'bindkey -e'

[plugins.zsh-syntax-highlighting]
github = "zdharma/fast-syntax-highlighting"

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"

[plugins.zsh-abbr]
#apply = ["defer"]
github = "olets/zsh-abbr"

[plugins.fzf-git]
github = "junegunn/fzf-git.sh"

#[plugins.enhancd]
#github = "b4b4r07/enhancd"
#apply = ["defer"]

[plugins.dotfiles]
local = "~/.zsh"
use = [
    "alias.zsh",
    "autosuggest.zsh",
    "broot.zsh",
    "cargo.zsh",
    "chezmoi.zsh",
    "direnv.zsh",
    "env.zsh",
    "fzf.zsh",
    "go.zsh",
    "google-cloud-sdk.zsh",
    "history.zsh",
    "hook.zsh",
    "jira.zsh",
    "keybinding.zsh",
    "krew.zsh",
    "local.zsh",
    "osc133.zsh",
    "saneopt.zsh",
    "setting.zsh",
    "starship.zsh",
    "wezterm.zsh",
    "zoxide.zsh",
    "zstyle.zsh",
]

[plugins.dotfiles-defers]
local = "~/.zsh"
apply = ["defer"]
use = ["mise.zsh", "abbr.zsh"]

[plugins.compinit]
inline = 'autoload -Uz compinit && compinit -C'
