[tools]
java = [
    "openjdk-17",
    "adoptopenjdk-11.0.20+101",
    "openjdk-19",
    "openjdk-21",
    "openjdk-24",
    "zulu-8",
]
go = "latest"
python = "3.11"
node = "24"
ruby = "3.3.4"

mysql = "8.0"

maven = "3.9"
gradle = "8"
pnpm = "latest"

kubectl = "latest"
krew = "latest"

awscli = "latest"
eksctl = "latest"
mill = "latest"
zig = ["0.14", "ref:master"]
deno = "latest"
bun = "latest"
ruff = "latest"
uv = "latest"
lefthook = "latest"
yamlfmt = "latest"
azure-cli = "latest"
dbmate = "latest"
just = "latest"
"npm:@openai/codex" = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:@github/copilot" = "latest"
"npm:@ast-grep/napi" = "latest"

[alias.java.versions]
8 = "zulu-8"
11 = "adoptopenjdk-11.0.20+101"
17 = "openjdk-17"
19 = "openjdk-19"
21 = "openjdk-21"
24 = "openjdk-24"

[settings]
idiomatic_version_file_enable_tools = ["python"]
