# Inserts a blank line between shell prompts
add_newline = true

format = """$all\
$kubernetes\
$sudo\
$cmd_duration\
$time\
$line_break\
$jobs\
$battery\
$status\
$container\
$shell\
$character"""

[kubernetes]
disabled = true
format = '[$symbol$context( \($namespace\)) ]($style)'

[kubernetes.context_aliases]
"kind-kind" = "kind"
"gke_.*_(?P<var_cluster>[\\w-]+)" = "gke-$var_cluster"

[env_var.DEVBOX_SHELL_ENABLED]
format = "ðŸ“¦[devbox](bold fg:green)"

[golang]
format = "[$symbol($version )]($style)"

[buf]
format = '[$symbol($version )]($style)'
symbol = "ðŸ¦¬ "

[aws]
disabled = true

[gcloud]
format = '[$symbol$account(@$domain)(\($region\)) ]($style)'
disabled = true

[scala]
disabled = true

[time]
disabled = false

[env_var.YAZI]
variable = "YAZI_LEVEL"
format = "ðŸ¦†Yazi\\($env_value\\) "

[direnv]
disabled = false
